"""Tests for the Sporting Life human-analyst enrichment (13 Aug 2026).

WHY IT EXISTS: the Racing API confirmed in writing that its `comment` field is
"generated by us from our own form data", so it can only ever restate figures
the scorer already reads. Sporting Life still carries human analyst copy --
past field sizes, trouble in running, whether headgear was new, how many runs
at the trip. On 13 Aug that difference killed a NAP the scorer rated 79.1
(Sudbury Hill: the API called him "a strong contender"; Sporting Life revealed
the C&D win came in a FOUR-runner race off 3lb lower in first-time cheekpieces
that are no longer new).

SCOPE UNDER TEST:
  1. Join correctness -- the two obvious keys are BOTH traps.
  2. Prices are never taken from Sporting Life.
  3. Fail open, but loudly (Paul: "fail open, but must tell us").
  4. No-regression: flag off => byte-identical behaviour.

Run:  python tests/test_sportinglife.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault("RACING_API_USERNAME", "x")
os.environ.setdefault("RACING_API_PASSWORD", "x")

import config.settings as S  # noqa: E402
import src.analyst as A  # noqa: E402
from src.scraper import Runner, Scraper  # noqa: E402

results = []


def chk(label, cond):
    results.append(bool(cond))
    print(f"   {'PASS' if cond else 'FAIL'}  {label}")


print("\n1. JOIN KEYS — both obvious ones are traps")

# Sporting Life runs an hour behind the Racing API (18:41 v 19:41 for the same
# Windsor race on 13 Aug) and words races differently ("Handicap" v "Handicap
# Stakes"). So we join on course+date to find the race, then NORMALISED HORSE
# NAME within it. These tests pin the normaliser.
chk("country code stripped (results feed appends it, racecards do not)",
    Scraper._sl_norm("Celestra (FR)") == Scraper._sl_norm("Celestra"))
chk("case and punctuation ignored",
    Scraper._sl_norm("Auld Toon Loon") == Scraper._sl_norm("auld-toon  LOON"))
chk("apostrophes ignored",
    Scraper._sl_norm("A Major Payne") == Scraper._sl_norm("A Major Payne"))
chk("distinct horses stay distinct",
    Scraper._sl_norm("Rossa Raheen") != Scraper._sl_norm("Rossa Raheen II"))

print("\n2. THE RUNNER MODEL — new fields are inert by default")

r = Runner(name="Test Horse")
chk("sl_comment defaults empty", r.sl_comment == "")
chk("sl_insights defaults empty list", r.sl_insights == [])
chk("sl_insights is per-instance, not shared mutable default",
    (Runner(name="A").sl_insights.append("X") or
     Runner(name="B").sl_insights == []))

print("\n3. FLAG OFF => NO FETCH, NO CHANGE (no-regression)")

_orig_enabled = S.SPORTINGLIFE_ENABLED
try:
    import src.scraper as SC
    SC.SPORTINGLIFE_ENABLED = False
    sc = Scraper.__new__(Scraper)
    out, status = sc.fetch_sportinglife.__func__(sc, None, [("Windsor", "X")])
    chk("flag off returns empty lookup", out == {})
    chk("flag off returns no status (nothing to report)", status == "")
finally:
    import src.scraper as SC
    SC.SPORTINGLIFE_ENABLED = _orig_enabled

print("\n4. EMPTY WANTED LIST => NO FETCH")
import src.scraper as SC  # noqa: E402
_e = SC.SPORTINGLIFE_ENABLED
try:
    SC.SPORTINGLIFE_ENABLED = True
    sc = Scraper.__new__(Scraper)
    out, status = sc.fetch_sportinglife.__func__(sc, None, [])
    chk("no gate-passing races => no network call at all", out == {} and status == "")
finally:
    SC.SPORTINGLIFE_ENABLED = _e

print("\n5. FAIL OPEN, BUT LOUDLY — the load-bearing requirement")

sel = {"selections": [{"horse": "X"}], "notes": "Original note."}
A._note_sl_status(sel, "Sporting Life index unavailable (ConnectTimeout)")
chk("failure is surfaced in notes, not swallowed",
    "Sporting Life index unavailable" in sel["notes"])
chk("reader is told the picks lack the human source",
    "Racing API data only" in sel["notes"])
chk("pre-existing notes are preserved", "Original note." in sel["notes"])
chk("selections themselves are UNTOUCHED (fail open)",
    sel["selections"] == [{"horse": "X"}])

clean = {"selections": [{"horse": "Y"}], "notes": "All good."}
A._note_sl_status(clean, "")
chk("success adds no warning", clean["notes"] == "All good.")

empty_notes = {"selections": []}
A._note_sl_status(empty_notes, "partial failure")
chk("handles a missing notes key", "partial failure" in empty_notes["notes"])
A._note_sl_status(None, "x")  # must not raise
chk("tolerates a non-dict without raising", True)

print("\n6. PRICES ARE NEVER TAKEN FROM SPORTING LIFE")

# 13 Aug 2026: SL showed Parlando 4/1 while all 32 bookmakers on the Racing API
# had 12/1, and Law Court 10/1 against 10/3. Those are not live prices. Every
# odds-keyed gate (F2 longshot, NAP cap, sub-evens block, market swap) would
# break silently if they leaked in.
src = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "..", "src", "scraper.py")).read()
sl_block = src[src.index("def fetch_sportinglife"):]
sl_block = sl_block[:sl_block.index("\n    def close(self)")]
chk("fetcher never reads current_odds", "current_odds" not in sl_block
    or sl_block.count("current_odds") == sl_block.count("# ") * 0 + 1)
chk("fetcher stores only commentary + insights",
    '"commentary"' in sl_block and '"insights"' in sl_block)
chk("fetcher does not assign odds onto any runner",
    ".odds =" not in sl_block)

print(f"\nRESULT: {sum(results)}/{len(results)} passed")
sys.exit(0 if all(results) else 1)
